# These are supported funding model platforms

github: pagegames # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://pagegames.github.io/sources/','https://pagegames.github.io/sources/']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

